apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/weaviate-default: "true"
    io.kompose.service: weaviate
  name: weaviate
  namespace: default
spec:
  containers:
    - args:
        - --host
        - 0.0.0.0
        - --port
        - "8080"
        - --scheme
        - http
      env:
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "true"
        - name: CLUSTER_HOSTNAME
          value: node1
        - name: DEFAULT_VECTORIZER_MODULE
          value: img2vec-neural
        - name: ENABLE_MODULES
          value: img2vec-neural
        - name: IMAGE_INFERENCE_API
          value: http://i2v-neural:8080
        - name: PERSISTENCE_DATA_PATH
          value: /var/lib/weaviate
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
      image: semitechnologies/weaviate:1.21.2
      name: weaviate
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
